---
- name: playbook
  hosts: rke2servers
  become: true
  tasks:
  - name: Register a partition variable
    shell: fdisk -l | grep '^Disk /dev/' | awk '{print $2 $3}' | grep 500
    register: lvm_partition
    
  - name: Block to create partition
    block:
      - name: Task for creating volume group (VG)
        lvg:
          vg: data-vg
          pvs: "{{ partition_name }}"  
  
      - name: task for LV
        lvol:
          vg: data-vg
          lv: "{{ item.first }}"
          size: "{{ item.second }}"
        with_items:
        - {first: rancher, second: 40G}
        - {first: depot-1v, second: 10G}

      - name: Formatting file system
        filesystem:
          dev: "{{item}}"
          fstype: xfs
        with_items:
          - "/dev/mapper/data--vg-rancher"
          - "/dev/mapper/data--vg-depot--1v"
      
      - name: Make directory
        file:
          path: "{{item}}"
          state: directory
        with_items:
          - "/var/lib/rancher"
          - "/depot"

      - name: FSTAB entry
        lineinfile:
          path: /etc/fstab
          regexp: "/var/lib/rancher"
          line: "/dev/mapper/data--vg-rancher /var/lib/rancher xfs defaults 0 0"
          state: present
          backup: yes
        register: fstab_rancher

      - name: FSTAB entry
        lineinfile:
          path: /etc/fstab
          regexp: "/depot"
          line: "/dev/mapper/data--vg-depot--1v /depot xfs defaults 0 0"
          state: present
          backup: yes
        register: fstab_depot

      - name: Mount the directories
        mount:
          path: "{{ item.first }}"
          src: "{{ item.second }}"
          fstype: xfs
          state: mounted
        with_items:
          - {first: "/var/lib/rancher", second: /dev/data-vg/rancher}
          - {first: /depot, second: /dev/data-vg/depot-1v}
    when: lvm_partition.stdout == "/dev/sdc:500"      
